---
title: Kombinasi Penggunaan Input
description: |
  Modul 6
author: 
  - name: Tedy Herlambang
    url: https://bangtedy.github.io
    orcid_id: 0000-0002-7296-4357
date: '2022-05-19'
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## PENDAHULUAN

Pada modul ini kita akan memperluas model produksi satu input satu output menjadi model multi input. Setelah mempelajari modul ini, mahasiswa diharapkan mampu menjelaskan konsep kombinasi penggunaan input lebih dari satu (satu output) dalam produksi pertanian. Secara khusus, mahasiswa diharapkan mampu menjelaskan:

- [x] konsep isoquant dan laju subtitusi marjinal;
- [x] maksimisasi keuntungan pada produksi dua input;
- [x] maksimisasi keuntungan pada dua input tanpa kendala;
- [x] maksimisasi keuntungan pada dua input dengan kendala.

<br />

## KEGIATAN BELAJAR
### A. PRODUKSI DENGAN DUA INPUT

- Secara matematis, produksi dengan dua input dapat dituliskan sebagai:

  $y = f(x_1,x_2)$


- Jika input lebih dari dua, input berikutnya ditulis:

  $y = f(x_1,x_2/x_3,...,x_n)$


### B. *ISOQUANT* DAN LAJU SUBSTITUSI MARJINAL

### C. BENTUK-BENTUK *ISOQUANT*

### D. MAKSIMISASI KEUNTUNGAN PADA DUA INPUT

#### 1. Maksimisasi Keuntungan tanpa Kendala

#### 2. Maksimisasi Keuntungan dengan Kendala

### E. PENGGANDA LAGRANGIAN

### F. GOVERNANSI EKONOMI PUPUK MAJEMUK



