---
title: Ekonomi Pertanian Indonesia
author: Tedy Herlambang
date: '2022-04-10'
slug: ekonomi-pertanian-indonesia
categories: [materi]
tags:
  - ekonomi pertanian
  - Indonesia
---

```{r load_packages, echo=FALSE}
library('fontawesome')
```

### `r fa("readme")` PENDAHULUAN

Modul 2 ini memberikan penjelasan lebih rinci tentang ekonomi pertanian Indonesia dari sisi ekonomi makro dan mikro. Secara umum setelah mempelajari modul 2 ini dengan baik mahasiswa diharapkan mampu menjelaskan kondisi dan masa depan ekonomi Indonesia. Secara khusus, setelah mempelajari Modul 2 ini, Anda diharapkan mampu:

- [x] menjelaskan kondisi dan masa depan ekonomi pertanian Indonesia
- [x] menjelaskan kinerja komoditas pertanian strategis di Indonesia
- [x] menjelaskan faktor skala ekonomi usahatani pada dimensi kesejahteraan

## `r emo::ji('books')` KEGIATAN BELAJAR

A. PERAN PERTANIAN DALAM PEMBANGUNAN EKONOMI

B. PERTUMBUHAN SEKTOR PERTANIAN

C. PERKEMBANGAN PRODUKSI PANGAN

D. PETANI DAN SKALA USAHATANI



<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_16 a2a_default_style"; data-a2a-url="https://bangtedy.github.io/etan" data-a2a-title="Ekonomi Pertanian Indonesia">
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_telegram"></a>
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->