---
title: Peran Pertanian Dalam Pembangunan Ekonomi
author: Tedy Herlambang
date: '2022-04-01'
slug: peran-pertanian-dalam-pembangunan-ekonomi
categories: []
tags:
  - peran pertanian
  - pembangunan ekonomi
---

### Kompetensi Umum

Setelah selesai mempelajari modul ini, mahasiswa mampu menjelaskan menjelaskan
esensi utama dari ekonomi pertanian.
 
### Kompetensi Khusus

1. Menjelaskan esensi dari ekonomi pertanian dalam kehidupan sehari-hari
2. Menjelaskan ruang lingkup ilmu ekonomi, khusus tentang kelangkaan sumber daya dan pilihan yang harus diambil seorang manusia.

---

### Kegiatan Belajar

### A. Ruang Lingkup Ekonomi

- Ilmu ekonomi adalah suatu cabang ilmu yang mempelajari penggunaan sumber daya yang "langka" untuk memenuhi keinginan manusia yang tidak terbatas. Dengan keterbatasan itulah, maka manusia harus melakukan "pilihan" untuk memenuhi keinginannya tadi, atau untuk memaksimumkan kepuasannya.

  - Konsumen harus memilih mengkonsumsi barang atau jasa yang mampu memberikan manfaat atau kepuasan maksimum dengan keterbatasan pendapatan atau anggaran yang dimilikinya.
  - Produsen juga harus mampu membuat pilihan produksi, distribusi dan investasi untuk menghasilkan keuntungan maksimum berdasarkan sumber daya atau anggaran yang dimiliknya.
  - Setelah mempertimbangkan biaya dan manfaat yang diperoleh, masyarakat pun harus membuat pilihan untuk melakukan alokasi sumber daya yang terbatas tersebut.
  
#### Tentang Kelangkaan

- Alam tidak menyediakan semuanya secara tanpa batas kepada manusia, dan makhluk hidup lain di muka bumi. Manusialah yang memiliki kemampuan untuk menentukan dan mengalokasikan sumber daya yang langka ini agar mampu memenuhi keinginan dan kepuasannya. 

- Mahatma Gandhi: ”alam sebenarnya telah menyediakan sumber daya yang cukup untuk memenuhi kebutuhan manusia, tapi tidak untuk menuruti keserakahannya”.

> Manusia tetap harus menentukan pilihan atau harus mengambil keputusan untuk
memilih karena pada hakikatnya sumber daya itu, yang sebenarnya ”cukup” memang terbatas, bukan tidak terbatas.

---

Pengelompokan Sumberdaya: (1) sumber daya alam dan biologi, (2) sumber daya manusia, dan (3) sumber daya buatan.

#### Sumber daya alam dan biologi:

- sumber daya lahan, hutan, lautan, mineral, galian, tambang, panas bumi dan lain-lain yang berada pada jurisdiksi negara Indonesia. 

- Indonesia memiliki hampir semua mineral, logam dan unsur kimia, hampir semua binatang dan tanaman --> negara mega-biodiversity. 
- Tetapi sumber daya alam dan biologi ini pasti masih terbatas karena tidak semuanya tersedia secara bebas kepada manusia, melainkan memerlukan syarat dan kualifikasi tertentu untuk memanfaatkannya.

#### Sumber daya manusia

- jasa yang disediakan atau ditawarkan oleh tenaga kerja beserta kemampuan manajerialnya dalam menghasilkan barang dan jasa tertentu. 

- Dalam konsep ekonomi, tenaga kerja ini disebut terbatas atau langka, walaupun suatu negara tidak berada pada tingkat penyerapan tenaga kerja penuh. 

- Jasa tenaga kerja ini amat tergantung pada kemampuan atau keterampilan yang dimiliki berdasarkan tingkat upah yang ditawarkan atau berdasarkan kemampuan perusahaan memberikan upah yang disepakati dengan penyedia tenaga kerja. 

- Sumber daya manusia juga meliputi manajemen atau jasa kewirausahaan atau kemampuan yang dimiliki seseorang untuk menciptakan lapangan usaha baru, mendirikan perusahaan, menjalankan kegiatan usaha tertentu, menanggulangi risiko, sampai pada melakukan supervisi terhadap penggunaan sumber daya perusahaan untuk mencapai tujuannya.

#### Sumber daya buatan

- modal (kapital) yang berupa mesin, alat, atau struktur tertentu yang sebenarnya juga langka. 

- Sumber daya buatan ini juga mencakup stok, cadangan atau inventaris yang dihasilkan pada tahun ini, tetapi baru digunakan pada tahun berikutnya: stok beras di Bulog untuk
menjaga stabilitas harga beras.

---

### B. DEFINISI EKONOMI

> ”Ekonomi adalah ilmu sosial yang mempelajari bagaimana konsumen,
produsen, dan masyarakat melakukan pilihan dari serangkaian alternatif
yang tersedia dan kemungkinan penggunaan sumber daya langka dalam
proses produksi, distribusi dan konsumsi barang dan jasa”

#### Ekonomi Mikro vs Ekonomi Makro

- Ekonomi mikro fokus pada kegiatan ekonomi yang dilakukan oleh individu atau kelompok tertentu dari individu-individu tersebut.

- Ekonomi makro membahas tingkah laku dan fenomena perekonomian secara agregat seperti
pertumbuhan ekonomi, produk domestik bruto (PDB) atau pendapatan nasional, kemiskinan, pengangguran, inflasi, hubungan terbalik antara tingkat pengangguran dan laju inflasi.

#### Ekonomi Positif vs Ekonomi Normatif

- Ekonomi positif fokus pada pertanyaan apa itu (what is) dan apa yang akan terjadi jika (what would happen if) dan isu-isu kebijakan.

- Dalam hal ini tidak ada suatu keputusan nilai (value judgement) tertentu atau
tidak terdapat saran, rekomendasi atau resep tertentu. 

- murni mengenai tingkah laku ekonomi dari produsen dan konsumen yang terjadi
atau akan terjadi sebagai reaksi dari suatu fenomena atau kebijakan tertentu.

#### Ekonomi Normatif 

- fokus pada pertanyaan apa sebaiknya (what should be) atau bagaimana seharusnya (what ought to be).

#### Sistem Ekonomi Pancasila sebagai Alternatif

- Sistem ekonomi yang dimaksud di sini adalah seperangkat kelembagaan yang mampu memungkinkan sumber daya yang langka ini digunakan untuk memenuhi kebutuhan manusia: hukum,norma, kebiasaan, etika dan nilai-nilai hidup lain yang diadopsi dan dijalankan oleh warga negara. 

- Sistem ekonomi *kapitalisme* sistem ekonomi pasar bebas, individu dapat memiliki sumber daya dan memiliki hak penuh untuk menggunakan sumber daya tersebut sesuai dengan waktu yang tersedia, dengan seminimal mungkin hambatan legal dari pemerintah.
  
  - Sistem harga menjadi signal utama dalam menentukan nilai sumber daya dan barang-barang ekonomi.

- Sistem ekonomi *sosialisme*: yang dikembangkan dan dijalankan melalui perencanaan
sentralistik. 

- Sumber daya biasanya dimiliki secara kolektif, pemerintah dapat saja memutuskan bagaimana sumber daya manusia dan sumber daya non-manusia dimanfaatkan dan dialokasikan menurut sekian sektor dalam perekonomian. 

- Harga-harga umumnya ditentukan pemerintah dan diadministrasikan kepada konsumen dan kepada petani.

> Kelemahan dan kelebihan sistem kapitalisme dan sistem sosialisme??

---

#### Sistem Ekonomi Pancasila

1. Perekonomian disusun sebagai usaha bersama berdasar atas asas kekeluargaan.
2. Cabang-cabang produksi yang penting bagi negara dan yang menguasai hajat hidup orang banyak dikuasai oleh negara.
3. Bumi dan air dan kekayaan alam yang terkandung di dalamnya dikuasai oleh negara dan dipergunakan untuk sebesar-besarnya kemakmuran rakyat.
4. Perekonomian nasional diselenggarakan berdasar atas demokrasi ekonomi dengan prinsip kebersamaan, efisiensi berkeadilan, berkelanjutan, berwawasan lingkungan, kemandirian, serta dengan menjaga keseimbangan kemajuan dan kesatuan ekonomi nasional.
5. Ketentuan lebih lanjut mengenai pelaksanaan pasal ini diatur dalam undang-undang.

---

### C. EKONOMI PERTANIAN

> “Ekonomi Pertanian adalah suatu cabang ilmu ekonomi terapan yang mempelajari beberapa hal tentang bagaimana produsen, konsumen dan masyarakat menggunakan dan memanfaatkan sumber daya yang langka ini dalam proses produksi, distribusi, dan konsumsi produk pertanian, terutama pangan dan sandang”.

#### Apa saja yang dikerjakan para ekonomi pertanian?

Secara ideal:

1. Peran pada Tingkat Ekonomi Mikro

Para ekonom pertanian telah berkiprah pada tingkat ekonomi mikro pada bidang-bidang yang berhubungan dengan pemanfaatan sumber daya di bidang produksi, pengolahan, distribusi, dan konsumsi produk pangan dan sandang.

2. Peran pada Tingkat Ekonomi Makro

- Para ekonom pertanian yang banyak berkiprah di tingkat ekonomi makro umumnya mengurusi peran pertanian dan sistem agribisnis dala perekonomian nasional dan perekonomian global. 
- Mereka fokus pada keterkaitan tentang bagaimana kejadian atau fenomena yang terjadi di sektor lain mempengaruhi kinerja perusahaan pertanian, atau sebaliknya. 

3. Peran pada Fenomena Perubahan

Salah satu kata kunci dalam memahami ilmu ekonomi pertanian dan ilmu ekonomi secara umum adalah prinsip analisis marginal atau fenomena perubahan.


<!-- AddToAny BEGIN -->
<div class="a2a_kit a2a_kit_size_16 a2a_default_style"; data-a2a-url="https://bangtedy.github.io/etan" data-a2a-title="Peran Pertanian Dalam Pembangunan Ekonomi">
<a class="a2a_button_whatsapp"></a>
<a class="a2a_button_telegram"></a>
<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
</div>
<script async src="https://static.addtoany.com/menu/page.js"></script>
<!-- AddToAny END -->